AWSTemplateFormatVersion: '2010-09-09'

Description: S3 Bucket Backup

Metadata:
  Author: Michael Ludvig <michael.ludvig@enterpriseit.co.nz>
  Description: |-
    Continuously mirror objects from S3 bucket to another account.

Parameters:
  SourceAccountId:
    Type: String
    Description: Source AWS Account ID

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Statement:
        - Action:
          - s3:PutObject
          - s3:PutObjectAcl
          Effect: Allow
          Resource: !Sub arn:aws:s3:::${Bucket}/*
          Principal:
            AWS: !Sub "arn:aws:iam::${SourceAccountId}:root"
          Condition:
            StringEquals:
              s3:x-amz-acl: bucket-owner-full-control
        - Action:
          - s3:PutObjectTagging
          - s3:DeleteObject
          - s3:DeleteObjectTagging
          Effect: Allow
          Resource: !Sub arn:aws:s3:::${Bucket}/*
          Principal:
            AWS: !Sub "arn:aws:iam::${SourceAccountId}:root"

Outputs:
  Bucket:
    Value: !Ref Bucket
